import { useEffect, useState, type FormEvent } from 'react'
import { apiRequest } from '../services/api'
import type { AuditLog, AuditLogList, RedemptionList, RedemptionRecord, StaffList, StaffUser } from '../types/api'

const PAGE_SIZE=20
const fmt=(v:string|null)=>v?new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(v)):'—'
const name=(nick:string|null,fallback:string)=>nick?.trim()||fallback

function Pager({page,total,onChange}:{page:number;total:number;onChange:(value:number)=>void}){const pages=Math.max(1,Math.ceil(total/PAGE_SIZE));return <footer className="pagination"><span>第 {page} / {pages} 页，共 {total} 条</span><div><button disabled={page<=1} onClick={()=>onChange(page-1)}>上一页</button><button disabled={page>=pages} onClick={()=>onChange(page+1)}>下一页</button></div></footer>}
function Loading({label}:{label:string}){return <section className="content-card empty-state"><div className="loading-ring"/><h2>正在加载{label}</h2></section>}
function Failed({message,retry}:{message:string;retry:()=>void}){return <section className="content-card empty-state"><div className="empty-icon">!</div><h2>加载失败</h2><p>{message}</p><button className="secondary-button compact-secondary" onClick={retry}>重新加载</button></section>}

export function RedemptionsPage(){
  const [items,setItems]=useState<RedemptionRecord[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[error,setError]=useState(''),[input,setInput]=useState(''),[q,setQ]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[selected,setSelected]=useState<RedemptionRecord|null>(null)
  async function load(){setLoading(true);setError('');const p=new URLSearchParams({page:String(page),page_size:String(PAGE_SIZE)});if(q)p.set('q',q);if(from)p.set('date_from',from);if(to)p.set('date_to',to);try{const r=await apiRequest<RedemptionList>(`/admin/redemptions?${p}`);setItems(r.items);setTotal(r.total)}catch(e){setError(e instanceof Error?e.message:'核销记录加载失败')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[page,q,from,to]);function search(e:FormEvent){e.preventDefault();setPage(1);setQ(input.trim())}
  return <div className="page-content"><header className="page-header"><div><p className="eyebrow">REDEMPTIONS</p><h1>签到与核销记录</h1><p>查看次卡扣减、期限卡签到及其操作来源。</p></div><div className="date-chip">共 {total} 条记录</div></header><section className="ops-toolbar"><form className="member-search" onSubmit={search}><input className="search-input" value={input} onChange={e=>setInput(e.target.value)} placeholder="记录号、会员、卡号、签到码或手机后四位"/><button className="secondary-button compact-secondary">搜索</button></form><div className="date-filter"><label>从<input type="date" value={from} onChange={e=>{setPage(1);setFrom(e.target.value)}}/></label><label>至<input type="date" value={to} onChange={e=>{setPage(1);setTo(e.target.value)}}/></label></div></section>
  {loading?<Loading label="签到与核销记录"/>:error?<Failed message={error} retry={()=>void load()}/>:items.length===0?<section className="content-card empty-state"><div className="empty-icon">✓</div><h2>暂无签到核销记录</h2><p>会员或员工完成首次操作后会显示在这里。</p></section>:<section className="member-table-card"><div className="member-table-wrap"><table className="member-table redemption-table"><thead><tr><th>时间</th><th>会员</th><th>会员卡</th><th>权益变化</th><th>来源</th><th>记录号</th><th/></tr></thead><tbody>{items.map(v=><tr key={v.id}><td><strong className="table-primary">{fmt(v.redeemed_at)}</strong></td><td><strong className="table-primary">{name(v.member_nickname,'微信会员')}</strong><small>{v.member_no} · {v.member_phone||'未授权手机'}</small></td><td><strong className="table-primary">{v.product_name}</strong><small>{v.card_no}</small></td><td>{v.before_remaining===null?<><strong className="balance-change">到店签到</strong><small>期限卡不扣次数</small></>:<><strong className="balance-change">{v.before_remaining} → {v.after_remaining}</strong><small>核销 {v.times} 次</small></>}</td><td><strong className="table-primary">{v.redemption_mode==='MEMBER_SELF_SCAN'?'会员自助扫码':name(v.operator_nickname,'员工')}</strong><small>{v.checkin_code_name||v.operator_member_no}</small></td><td><strong className="mono-value">{v.redemption_no}</strong></td><td><button className="detail-button" onClick={()=>setSelected(v)}>查看</button></td></tr>)}</tbody></table></div><Pager page={page} total={total} onChange={setPage}/></section>}
  {selected&&<div className="modal-backdrop member-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><section className="member-drawer"><header><div><p className="eyebrow">REDEMPTION DETAIL</p><h2>{selected.before_remaining===null?'签到详情':'核销详情'}</h2><small>{selected.redemption_no}</small></div><button className="modal-close" onClick={()=>setSelected(null)}>×</button></header><div className="member-detail-body"><section className="detail-metrics"><div><span>业务类型</span><strong>{selected.before_remaining===null?'到店签到':`扣减 ${selected.times} 次`}</strong></div><div><span>操作来源</span><strong>{selected.redemption_mode==='MEMBER_SELF_SCAN'?'会员自助扫码':'员工扫码'}</strong></div></section><section className="detail-section"><h3>业务信息</h3><dl className="detail-list"><div><dt>会员</dt><dd>{name(selected.member_nickname,'微信会员')} · {selected.member_no}</dd></div><div><dt>手机号</dt><dd>{selected.member_phone||'未授权'}</dd></div><div><dt>会员卡</dt><dd>{selected.product_name} · {selected.card_no}</dd></div><div><dt>权益变化</dt><dd>{selected.before_remaining===null?'当日签到已记录':`${selected.before_remaining} → ${selected.after_remaining}`}</dd></div></dl></section><section className="detail-section"><h3>操作追踪</h3><dl className="detail-list"><div><dt>签到码</dt><dd>{selected.checkin_code_name||'—'}</dd></div><div><dt>操作人</dt><dd>{name(selected.operator_nickname,selected.redemption_mode==='MEMBER_SELF_SCAN'?'会员':'员工')} · {selected.operator_member_no}</dd></div><div><dt>操作时间</dt><dd>{fmt(selected.redeemed_at)}</dd></div><div><dt>请求 ID</dt><dd className="break-value">{selected.request_id}</dd></div></dl></section></div><footer><button className="secondary-button compact-secondary" onClick={()=>setSelected(null)}>关闭</button></footer></section></div>}</div>
}

export function StaffPage(){
  const [items,setItems]=useState<StaffUser[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[role,setRole]=useState<'ALL'|'MEMBER'|'STAFF'>('STAFF'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[input,setInput]=useState(''),[q,setQ]=useState(''),[notice,setNotice]=useState('')
  async function load(){setLoading(true);setError('');const p=new URLSearchParams({page:String(page),page_size:String(PAGE_SIZE)});if(q)p.set('q',q);if(role!=='ALL')p.set('role',role);try{const r=await apiRequest<StaffList>(`/admin/staff?${p}`);setItems(r.items);setTotal(r.total)}catch(e){setError(e instanceof Error?e.message:'员工列表加载失败')}finally{setLoading(false)}}useEffect(()=>{void load()},[page,q,role]);function search(e:FormEvent){e.preventDefault();setPage(1);setQ(input.trim())}
  async function changeRole(user:StaffUser){const next=user.role==='STAFF'?'MEMBER':'STAFF';if(!window.confirm(next==='STAFF'?`确认授予“${name(user.nickname,user.member_no)}”员工核销权限吗？`:`确认撤销“${name(user.nickname,user.member_no)}”的员工权限吗？`))return;setNotice('');try{const updated=await apiRequest<StaffUser>(`/admin/users/${user.id}/role`,{method:'PUT',body:JSON.stringify({role:next,version:user.version})});setItems(v=>role==='STAFF'&&next==='MEMBER'?v.filter(x=>x.id!==user.id):v.map(x=>x.id===updated.id?updated:x));setTotal(v=>role==='STAFF'&&next==='MEMBER'?Math.max(0,v-1):v);setNotice(next==='STAFF'?'员工权限已授予':'员工权限已撤销')}catch(e){setNotice(e instanceof Error?e.message:'角色修改失败')}}
  return <div className="page-content"><header className="page-header"><div><p className="eyebrow">STAFF ACCESS</p><h1>员工管理</h1><p>从微信会员中授权员工核销权限，管理员账号不在此处管理。</p></div><div className="date-chip">{role==='STAFF'?`${total} 位员工`:`${total} 位用户`}</div></header><section className="member-toolbar"><div className="filter-tabs">{([['STAFF','现有员工'],['MEMBER','选择会员'],['ALL','全部']] as const).map(([v,l])=><button key={v} className={role===v?'active':''} onClick={()=>{setPage(1);setRole(v)}}>{l}</button>)}</div><form className="member-search" onSubmit={search}><input className="search-input" value={input} onChange={e=>setInput(e.target.value)} placeholder="会员号、昵称或手机后四位"/><button className="secondary-button compact-secondary">搜索</button></form></section>{notice&&<div className="page-notice">{notice}</div>}
  {loading?<Loading label="员工"/>:error?<Failed message={error} retry={()=>void load()}/>:items.length===0?<section className="content-card empty-state"><div className="empty-icon">♙</div><h2>{role==='STAFF'?'还没有员工':'没有符合条件的会员'}</h2><p>{role==='STAFF'?'切换到“选择会员”授予员工权限。':'请更换搜索条件。'}</p></section>:<section className="staff-grid">{items.map(v=><article className="staff-card" key={v.id}><div className="staff-avatar">{v.avatar_url?<img src={v.avatar_url} alt=""/>:<span>{name(v.nickname,'员').slice(0,1)}</span>}</div><div className="staff-info"><div><span className={`member-status ${v.status.toLowerCase()}`}>{v.status==='ACTIVE'?'正常':'已禁用'}</span><span className={`role-badge ${v.role.toLowerCase()}`}>{v.role==='STAFF'?'员工':'会员'}</span></div><h2>{name(v.nickname,'微信会员')}</h2><p>{v.member_no}</p><dl><div><dt>手机号</dt><dd>{v.phone||'未授权'}</dd></div><div><dt>微信</dt><dd>{v.wechat_bound?'已绑定':'未绑定'}</dd></div><div><dt>最近登录</dt><dd>{fmt(v.last_login_at)}</dd></div></dl><button className={v.role==='STAFF'?'danger-outline':'primary-button compact'} disabled={v.status!=='ACTIVE'} onClick={()=>void changeRole(v)}>{v.role==='STAFF'?'撤销员工权限':'授予员工权限'}</button></div></article>)}</section>}{!loading&&!error&&items.length>0&&<Pager page={page} total={total} onChange={setPage}/>}</div>
}

const actionLabels:Record<string,string>={CARD_PRODUCT_CREATE:'创建会员卡商品',CARD_PRODUCT_UPDATE:'修改会员卡商品',CARD_PRODUCT_STATUS_CHANGE:'商品上下架',MEMBER_UPDATE:'修改会员资料',USER_ROLE_UPDATE:'修改员工权限',CHECKIN_CODE_CREATE:'创建签到码',CHECKIN_CODE_STATUS_CHANGE:'启停签到码',CHECKIN_CODE_REGENERATE:'更换签到码',MEMBER_SELF_CHECKIN:'会员自助签到'}
export function AuditLogsPage(){
  const [items,setItems]=useState<AuditLog[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[error,setError]=useState(''),[input,setInput]=useState(''),[q,setQ]=useState(''),[resource,setResource]=useState(''),[selected,setSelected]=useState<AuditLog|null>(null)
  async function load(){setLoading(true);setError('');const p=new URLSearchParams({page:String(page),page_size:String(PAGE_SIZE)});if(q)p.set('q',q);if(resource)p.set('resource_type',resource);try{const r=await apiRequest<AuditLogList>(`/admin/audit-logs?${p}`);setItems(r.items);setTotal(r.total)}catch(e){setError(e instanceof Error?e.message:'审计日志加载失败')}finally{setLoading(false)}}useEffect(()=>{void load()},[page,q,resource]);function search(e:FormEvent){e.preventDefault();setPage(1);setQ(input.trim())}
  return <div className="page-content"><header className="page-header"><div><p className="eyebrow">AUDIT TRAIL</p><h1>审计日志</h1><p>追踪管理员对商品、会员、员工、签到码和退款的关键操作。</p></div><div className="date-chip">不可修改 · 共 {total} 条</div></header><section className="member-toolbar"><div className="filter-tabs">{([['','全部'],['CARD_PRODUCT','商品'],['MEMBER','会员'],['USER','员工'],['CHECKIN_CODE','签到码'],['ORDER','订单']] as const).map(([v,l])=><button key={v} className={resource===v?'active':''} onClick={()=>{setPage(1);setResource(v)}}>{l}</button>)}</div><form className="member-search" onSubmit={search}><input className="search-input" value={input} onChange={e=>setInput(e.target.value)} placeholder="资源 ID、请求 ID 或管理员"/><button className="secondary-button compact-secondary">搜索</button></form></section>
  {loading?<Loading label="审计日志"/>:error?<Failed message={error} retry={()=>void load()}/>:items.length===0?<section className="content-card empty-state"><div className="empty-icon">≡</div><h2>暂无审计日志</h2><p>管理员完成关键操作后会自动记录。</p></section>:<section className="audit-timeline">{items.map(v=><article className="audit-item" key={v.id}><div className="audit-dot"/><div className="audit-card"><header><div><strong>{actionLabels[v.action]||v.action}</strong><span>{v.resource_type} · {v.resource_id}</span></div><time>{fmt(v.created_at)}</time></header><p>操作者：{v.operator_name||'系统'}{v.request_ip?` · IP ${v.request_ip}`:''}</p><footer><code>{v.request_id}</code><button className="detail-button" onClick={()=>setSelected(v)}>查看变更</button></footer></div></article>)}</section>}{!loading&&!error&&items.length>0&&<Pager page={page} total={total} onChange={setPage}/>} {selected&&<div className="modal-backdrop member-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><section className="member-drawer"><header><div><p className="eyebrow">AUDIT DETAIL</p><h2>{actionLabels[selected.action]||selected.action}</h2><small>{fmt(selected.created_at)}</small></div><button className="modal-close" onClick={()=>setSelected(null)}>×</button></header><div className="member-detail-body"><section className="detail-section"><h3>追踪信息</h3><dl className="detail-list"><div><dt>资源</dt><dd>{selected.resource_type} · {selected.resource_id}</dd></div><div><dt>操作者</dt><dd>{selected.operator_name||'系统'}</dd></div><div><dt>请求 IP</dt><dd>{selected.request_ip||'—'}</dd></div><div><dt>请求 ID</dt><dd className="break-value">{selected.request_id}</dd></div></dl></section><section className="snapshot-section"><h3>变更前</h3><pre>{selected.before?JSON.stringify(selected.before,null,2):'无'}</pre></section><section className="snapshot-section"><h3>变更后</h3><pre>{selected.after?JSON.stringify(selected.after,null,2):'无'}</pre></section></div><footer><button className="secondary-button compact-secondary" onClick={()=>setSelected(null)}>关闭</button></footer></section></div>}</div>
}
